### ISSUE TITLE
Add location to VibeEvent

### ISSUE THREAD

**Issue by jacobwong98** [CMPUT301F19T02/Vybe#102]

**Comment by raysarinas** [comment]
This is the same issue as #57 ?

**Comment by raysarinas** [comment]
This is a duplicate issue for Issue #57 

Please look in backlog first next time before making a new issue I guess. I am closing this issue, so please be sure to rename the branch with work from this issue to being related to issue 57. Probably can rename the branch using something in here: https://stackoverflow.com/questions/36999937/rename-a-git-branch-locally-and-remotely
