### ISSUE TITLE
Lock App to Vertical Orientation

### ISSUE THREAD

**Issue by raysarinas** [CMPUT301F19T02/Vybe#127]
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: N/A

[//]: # (Please Add labels for type of issue)

Description: This is just a nice-to-have so we don't run into the issues of weird scrolling things happening messing up our UI. 

Just an optional thing to consider if we have time later in the future I guess.

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 1

Related Issues: N/A

References: 
https://stackoverflow.com/questions/40332951/how-to-set-app-to-be-portrait-only

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

**Comment by EPostill** [comment]
it has been done

**Comment by raysarinas** [comment]
This needs to be reviewed first before closing lol
