### ISSUE TITLE
Look Into Replacing ListViews with RecyclerViews

### ISSUE THREAD

**Issue by raysarinas** [CMPUT301F19T02/Vybe#131]
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: N/A

[//]: # (Please Add labels for type of issue)

Description: Read [this](https://developer.android.com/guide/topics/ui/layout/recyclerview). Might help with performance issues we have been having. 

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 8

Related Issues: N/A

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

**Comment by gatilogo** [comment]
Links that might be helpful:
https://traversoft.com/2016/01/31/replace-listview-with-recyclerview/
https://codeburst.io/android-swipe-menu-with-recyclerview-8f28a235ff28

**Comment by raysarinas** [comment]
This issue can be closed because we have decided to completely move to using RecyclerViews. Implementation is to be done under Issues #133 and #53.
