### ISSUE TITLE
Use Wrapper Class for Latitude/Longitude

### ISSUE THREAD

**Issue by raysarinas** [CMPUT301F19T02/Vybe#135]
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: N/A

[//]: # (Please Add labels for type of issue)

Description: I believe we have come to the issue of not being able to or somehow also being able to set our Vibe Event locations to null. I think we can also get rid of having to always initialize our location as `this.latitude = 0;` and `this.longitude = 0;` in the `VibeEvent` constructor by using the Java wrapper functions for doubles. The types for `latitude` and `longitude` are currently `double` but we might be able to get around whatever issues we have been having by replacing all of those instances of `double` with `Double` which is a Java wrapper class that _can_ be set to `null`. Would like more feedback on this from @TheBroMoe. Afterwards should talk to @EPostill with whatever related issues there have been with having to initialize and set location to `(0, 0)`

Related Resources:
 - https://stackoverflow.com/questions/12226757/java-different-double-and-double-in-comparison
 - https://softwareengineering.stackexchange.com/a/203974 (Be sure to read this answer)

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 3

Related Issues: N/A

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

**Comment by TheBroMoe** [comment]
I agree this should be worked on if we would prefer lat and lon values to be null at different points in the codebase. This would be switching `double` to `Double`, reassigning nulls wherever necessary and also adding code to handle for NullPointerExceptions as mentioned in the provided resources.
