### ISSUE TITLE
Close Background Activites

### ISSUE THREAD

**Issue by jacobwong98** [CMPUT301F19T02/Vybe#140]
Need to refactor our intents to close all background activities that may be running because the app seems to lose performance when multiple activities/fragments are created.

This line below should kill all background activites when we call startActivity with this intent flag added
`intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);`

**Comment by raysarinas** [comment]
We should also look into seeing if our activities running in the background constantly listening for changes (i.e. in the ListView activities) are why performance is slowing down? I guess that is worth considering

**Comment by raysarinas** [comment]
Okay I guess not because we fixed everything
