### ISSUE TITLE
Refactor ALL XML Files

### ISSUE THREAD

**Issue by raysarinas** [CMPUT301F19T02/Vybe#178]
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: N/A

[//]: # (Please Add labels for type of issue)

Description: Issue to be done last, final refactoring issue for ensuring our UI looks exactly as we want it to (or match it to be as close as possible to as to how we have our mockups). 

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 8

Related Issues: N/A

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

**Comment by TheBroMoe** [comment]
Are we sure this shouldn't be broken down into smaller issues?

**Comment by raysarinas** [comment]
> Are we sure this shouldn't be broken down into smaller issues?

No, this is more of a last minute thing since the XML files are going to be changed as we are continuing to refactor! Plus modifying the XML files should have like zero effect on any of the actual Java code

**Comment by raysarinas** [comment]
Also, since the XML files aren't going to interact with each other, multiple people can work on different XML files at once in the same branch without any conflicts
