### ISSUE TITLE
Conflicting ImageViews on AddEditVibeActivity

### ISSUE THREAD

**Issue by jacobwong98** [CMPUT301F19T02/Vybe#180]
On AddEditVibeActivity, there is an ImageView used to display the reason image associated with the VibeEvent (for edit). Then there is also another ImageView that is in the Image field fragment that is used to hold the image that the user uploads. Do we need to have both ImageViews? Which one should I clear when they click the Remove Image button

Related: #168

**Comment by raysarinas** [comment]
To Be Completed under Branch #158
