### ISSUE TITLE
Viewing Profile sometimes shows the wrong button

### ISSUE THREAD

**Issue by TheBroMoe** [CMPUT301F19T02/Vybe#191]
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: N/A

Description: Writing tests from issue #155 has shown that a user viewing their personal profile does not always display the correct button. I think that the way we're doing our checks for which button to display when clicking on a profile should be changed in either one of the following ways:

1. Having a separate XML file for a personal vs a social profile
2. Having better checks for which button to display

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)
![testIssue](https://user-images.githubusercontent.com/32118276/69669278-c82b5d00-104e-11ea-8c33-38b481a7e4df.JPG)

Story Points: 3

Related Issues: #150 

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

**Comment by raysarinas** [comment]
None of us can recreate this issue so this issue may be invalidated

**Comment by raysarinas** [comment]
This issue only came up as a result of incomplete tests creating and failing to delete accounts correctly.
