### ISSUE TITLE
Have espresso tests check toast messages

### ISSUE THREAD

**Issue by TheBroMoe** [CMPUT301F19T02/Vybe#194]
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: N/A

[//]: # (Please Add labels for type of issue)

Description: Currently testing for functionality is passible, however further verification of ensuring we get the correct error message by checking the toast should be considered if time allows it.

This can be done by referring to the following [link](https://stackoverflow.com/questions/28390574/checking-toast-message-in-android-espresso)

The reason this would be difficult to do is the entire toast message would have to be hard coded typed unless we do this after doing issue #151 

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 2

Related Issues: N/A

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

**Comment by raysarinas** [comment]
Due to time constraints, won't be able to work on this issue
