### ISSUE TITLE
Finish Project Part 1

### ISSUE THREAD

**Issue by TheBroMoe** [CMPUT301F19T02/Vybe#2]
Do the following:
1. Fork the Repo
2. Clone Repo and create personal branch
3. Commit personal entry to `Team.txt`
4. Push to branch and submit PR to master

**Comment by raysarinas** [comment]
What does "Commit personal entry" mean? Also can we change our organization picture to Kirk Van Houten please and thank you.

**Comment by gatilogo** [comment]
> What does "Commit personal entry" mean? Also can we change our organization picture to Kirk Van Houten please and thank you.

Add a line with your CCID and GitHub username separated by a space
