### ISSUE TITLE
Complete Product Backlog

### ISSUE THREAD

**Issue by TheBroMoe** [CMPUT301F19T02/Vybe#25]
We have attempted to complete the backlog. Scrum Master @raysarinas  Give it a lookover and give us feedback plz <3

**Comment by raysarinas** [comment]
It looks fine I guess, but we do need stories for setting up our base code, integrating certain features/parts of the app together, and investigating/looking into how to use some of the non-Android stuff like Firestore, Google Maps API. We can refine and figure out what else might need to be changed in detail later on (like Tuesday?) but if you guys could add those stories that'd be good.

**Comment by raysarinas** [comment]
Also, shouldn't what we are working on for Part 2 be their own stories? Like creating the UML, filling out the wiki, mockup UI/storyboards be their own stories? Just because those things could all be broken down into tasks that we can take on our own and/or work together on

**Comment by EPostill** [comment]
me and moe talked a lot about that. my idea was to have a separate page for the big user stories, and utilize what is now the product backlog page as where we keep the smaller individual tasks

**Comment by raysarinas** [comment]
Like what do you mean by that? lol also, if you guys can, could you re-order/rank the stories in the list? If that's possible, just by priority and more or less what actually needs to get done first (like I think we all agree that the map stories would just go all the way to the bottom of the list).
