### ISSUE TITLE
Complete Storyboard Sequence

### ISSUE THREAD

**Issue by TheBroMoe** [CMPUT301F19T02/Vybe#28]
- [x] Look into using Figma
- [x] Decide on what how to put together story board
- [x] Discuss with everyone how we are going to story board everything
- [x] Put together story board (At least 2 people working on this pls)

**Comment by raysarinas** [comment]
- Took too long to figure out how to use Figma, so switching over to MockFlow
- Trishia and I have started working on putting everything together for the mockup
