### ISSUE TITLE
01.01.01 Part 1 - add mood event attributes

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#32]
As a participant, I want my mood events to contain the current date and time, a required emotional state, and optional reason and social situation, so i can view the specific details of my moods

Story points:3

#8

We have refined this story, tasks to do (and present on Trello) are:

- [x] Make helper classes for mood event 
- [ ] Activity/XML stuff for emostate and mood event
- [ ] unit test mood event class and emotional state class
- [ ] Link task classes to firestore
- [ ] review

**Comment by raysarinas** [comment]
Refining our current work based on what was accomplished under Issue #63 , this issue will be closed and considered invalid, once a merge request to close Issue #63 is made. Any further work on completing the user requirement related to this issue will be done under Issue #79
