### ISSUE TITLE
01.01.01 Part 2 - add mood to mood history

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#34]
As a participant, I want to add a mood event to my mood history, so I can refer to it in the future

Story points: 5

- [x] Create Custom MoodList Class adapter
- [x] Create Mood History Activity
- [ ] Create Functionality to add mood to Firebase Database
- [ ] Write Unit Tests
- [ ] Update Documentation

- [ ] Review

#8

**Comment by raysarinas** [comment]
Refining our current work based on what was accomplished under Issue #63 , this issue will be closed and considered invalid, once a merge request to close Issue #63 is made. Any further work on completing the user requirement related to this issue will be done under Issue #79
