### ISSUE TITLE
Mood Emoticons and Colors

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#35]
User Requirement: 01.02.01 #9 

Requirement: As a participant, I want consistent emoticons and colors, so I can easily distinguish the emotional states in any view

Story Points: 8

Task List:
- [x] Decide on what set of emotional states we are going to be using
- [x] Make the actual set of emotional states for us to use
- [x] Look into modifying emotional state class to handle the actual set of emotional states we decide on using (investigating how to interface with UI)
- [x] Actually interface the set of emotional states with UI
- [x] ~~Integrate with Firestore~~ Moved to separate issue
- [x] Junit Tests (See if colors/emo states properly extracted from database and/or just also properly selected)
- [x] ~~Update Documentation - This includes the wiki~~ Moved to separate issue

**Comment by raysarinas** [comment]
If necessary, we can add a unit test for making sure trying to instantiate an AbstractVibe raises an Exception properly.
