### ISSUE TITLE
02.01.01 Part 1 - add reason to mood event

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#39]
As a participant, I want to express the reason why for a mood event using a brief textual explanation, to allow for further description

Story Points: 2

#13

Task List:
- [x] Ensure 'Reason' is a field in MoodEvent object with appropriate Getters/Setters
- [x] For UI, make sure Reason is actually an EditText parameter
- [ ] Ensure Reason is a parameter in Firestore
- [ ] Update Documentation if necessary

**Comment by raysarinas** [comment]
Refining our current work based on what was accomplished under Issue #63, this issue will be closed and considered invalid, once a merge request to close Issue #63 is made. Any further work on completing the user requirement related to this issue will be done under Issue #79
