### ISSUE TITLE
Implement Enums for Social Situation Dropdown Selector

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#41]
User Requirement: 02.03.01 

Description: As a participant, I want to specify the social situation for a mood event to be one of: alone, with one other person, with two to several people, or with a crowd, so I can see how social situations affect my mood

Points: 2

#15

Task List: 
- [x] Look into how to use a dropdown list (if we don't have a resource for that already)
- [x] Implement dropdown list for choosing a Social Situation

**Comment by raysarinas** [comment]
@TheBroMoe suggesting using enums for the different social situations we can pick from

**Comment by raysarinas** [comment]
Refining our current work based on what was accomplished under Issue #63 , this issue can be closed and considered invalid, once a merge request to close Issue #63 is made. 

Will need further discussion since this Issue is small enough to be dealt with as a single task under Issue #79.

**Comment by raysarinas** [comment]
Work for this issue was smaller than estimated and was completed under Issue #79.

**Comment by raysarinas** [comment]
After further consideration, issue needs to be re-opened and need to change how social situation dropdown selector works. Some work done under issue #79 and #37 but was reverted and will now be completed under this issue

**Comment by raysarinas** [comment]
Because of further complications with the amount of refactoring that is needed to be done, this issue will be closed by #110
