### ISSUE TITLE
Create User Profile Page

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#42]
Rationale: As a participant, I want to be able to create and view the details of a new profile with a unique username, so I can be identified by other users

Description: Create an XML file for personal user page that gets the correct log in/user information. An activity is already created for viewing a personal user page/profile and just need to fill in the correct functionality. Make sure personal user page gets correct information from database. 

NOTE: 
- Requires Issue #43 to be closed and completed before being worked on. 
- The user profile page can and most likely will extend to **other** user profile pages. May require hiding some information on a profile page that is not the user's

Story Points: 5

#16

**Comment by raysarinas** [comment]
This issue will also complete the work needed to be done by Issue #46

**Comment by raysarinas** [comment]
Reopening this issue because we have found that the profile page does not necessarily always work when logging in and out as a different user. That is, the profile page does not display anything if trying to log in or out as a different user. 

![Screenshot_1574055757](https://user-images.githubusercontent.com/32996140/69031604-b2a39c80-0997-11ea-93bb-657c8acaa438.png)

**Comment by jacobwong98** [comment]
> 
> 
> Reopening this issue because we have found that the profile page does not necessarily always work when logging in and out as a different user. That is, the profile page does not display anything if trying to log in or out as a different user. Please look into this @jacobwong98
> 
> ![Screenshot_1574055757](https://user-images.githubusercontent.com/32996140/69031604-b2a39c80-0997-11ea-93bb-657c8acaa438.png)

Yeah so this is because I haven't applied the updated queries. It should get fixed in issue #124  and I will also need to delete all the current users once this is done because they won't fit the new db structure

**Comment by jacobwong98** [comment]
Creating a new account
![image](https://user-images.githubusercontent.com/32500822/69082120-b4537b80-09fc-11ea-8b9c-c6f16f4e8404.png)
Viewing this profile
![image](https://user-images.githubusercontent.com/32500822/69082156-c2a19780-09fc-11ea-8b74-b9a916a359ca.png)
