### ISSUE TITLE
Login to Profile Functionality

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#43]
User Requirement: 03.01.01

Rationale: As a participant, I want to be able to log into my profile with my username and password, so I can persistently use the app

Description: Refine the login page to be able to create a user profile such that if a user enters a unique ID that does not already exist, the account gets created in the database and sends them to the myVibes activity. If a user enters an existing account and their password,  it will log them in by verifying the account in the database. Otherwise display a prompt that indicates a user has entered invalid credentials or the account does not exist (this should be a Toast).

Story Points: 13

#16

**Comment by raysarinas** [comment]
Pranav wants to review changes to make sure changes made are correct and appropriate for User model class. See Issue #119 for reversion
