### ISSUE TITLE
View Other User Profile

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#45]
Rationale: As a participant, I want to be able to view other users profiles, so that I can view their profile details

Description: Be able to click on a different user profile and display appropriate information. Ths issue may not necessarily be needed if full functionality is correctly implemented in Issue #42 . This issue must be done AFTER #50 

Story Points: 5

#16

**Comment by TheBroMoe** [comment]
Being closed as this is covered in issue #50

**Comment by raysarinas** [comment]
Separate classes/methods for query for user and when you tap on your own profile it would query for yourself and otherwise if on search, query for that user
