### ISSUE TITLE
04.01.01 Part 1 - personal mood history page

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#47]
As a participant, I want a page that contains my personal mood history, so I can look through past moods

Story Points 8

#17

Task List:
- [x] Create Custom List Class to Handle Vibe Objects
- [x] UI Implementation of ListView for Mood History Page/Activity
- [ ] Modify content.xml if necessary
- [ ] Integrate List with Database/Firestore - See Database Lab Participation for Reference
- [ ] JUnit Testing
- [ ] Update Documentation
- [ ] Code Review

**Comment by raysarinas** [comment]
Refining our current work based on what was accomplished under Issue #63 , this issue will be closed and considered invalid, once a merge request to close Issue #63 is made. Any further work on completing the user requirement related to this issue will be done under Issue #79
