### ISSUE TITLE
Sort Mood History

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#48]
User Requirement: 04.01.01

Description: As a Participant, I want my personal mood history to be sorted in reverse chronological order, so I can see the most recent ones easily, and scroll down to see my past moods.

Story Points: 2

#17

Task List
- [x] decide to sort mood events in the database or in the viewable list
- [x] based on decision, implement sorting methodology

**Comment by raysarinas** [comment]
[Possible Reference](https://developer.android.com/reference/java/util/Collections.html#sort(java.util.List%3CT%3E,%20java.util.Comparator%3C?%20super%20T%3E))

**Comment by jacobwong98** [comment]
Got this to work, will implement/fully complete this issue once other issues are resolved first
