### ISSUE TITLE
Follow Request Response Functionality

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#54]
User Requirement: 05.02.01

Rationale: As a participant, I want to accept the requests of other users to follow my profile, so I can control who sees my recent moods

Description: Decide on process for being able to accept and/or decline follow request and then implement appropriate methodology for accepting or declining a request. Then update lists based on option selected. 

- Depends on Issue #53 - Make sure there are buttons to accept/deny. This issue only requires filling in the functionality for said buttons.

- Consider duplicate cases in following/follower/request lists

- On ACCEPT REQUEST - Update "Following" list for requester, and update "Followers" list for current user/self, and remove requester from "Requests"

Potential References: 
["Instagram" Tutorial](https://www.youtube.com/watch?v=qoTjnhSCre0)

Note: This story/issue will be required to be updated as other functionality and issues are completed to ensure that we are on the right track of implementing the user requirement as we want. 

Story Points: 13

#20

**Comment by raysarinas** [comment]
Functionality for follow request response will be completed under the branch for issue #53
