### ISSUE TITLE
05.03.01 Part 2 - chronological order for followed mood list

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#56]
As a participant, I want the moods of those I follow to be sorted in reverse chronological order, so I can easily access recent moods

Story Points: 2

#21

Task List
- [ ] Use same sorting method from #48 
- [ ] pass followed user info into list

**Comment by raysarinas** [comment]
This issue is closely related to #48, which took little-to-no time to complete so chronological ordering for an event list can be done under issue #55 as a simple task (i.e. ordering is essentially one line of code that needs to be written)
