### ISSUE TITLE
Map View for Personal Mood History

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#58]
User Requirement: 06.02.01 

Description: As a participant, I want a map view containing my mood events that have locations, so I can see which locations affect my mood

Story Points: 13

#23

Task List
- [x] Look into Google Maps API if that's what we want to use and document findings
- [x] Create empty map xml
- [x] Allow map to access location data from mood event list
- [x] Display Mood events at their specified location

**Comment by raysarinas** [comment]
Good idea to look at mine and Jacob's hackathon app for some reference on using Google Maps API: https://github.com/raysarinas/Spottoke

**Comment by raysarinas** [comment]
For reference on custom markers so we can display our own vibes on the map: https://developers.google.com/maps/documentation/android-sdk/marker

**Comment by raysarinas** [comment]
Work this issue is being done concurrently with issue #57 and will be closed by it.
