### ISSUE TITLE
Create Code Base

### ISSUE THREAD

**Issue by PranavB6** [CMPUT301F19T02/Vybe#63]
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: Various

[//]: # (Please Add labels for type of issue)

Description: Create Code Base

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 8

Related Issues: ~~#32 #33 #34 #47~~ #34 #79 

Task List

- [x] Create Android Studio Project
- [x] Get basic functionality and outline of project working
- [x] Refine Issues/Stories
- [ ] ~~Unit Tests~~ Move to separate issue
- [ ] ~~Intent Tests~~ Move to separate issue
- [x] UML Updated
- [ ] Documentation Updated (Wiki and Storyboards)

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

**Comment by raysarinas** [comment]
Refining our current work based on what was accomplished under this issue, this issue will be closed once our Firestore requirements (as set up in Issue #65) are completed.
