### ISSUE TITLE
Refactor Onclick methods 

### ISSUE THREAD

**Issue by TheBroMoe** [CMPUT301F19T02/Vybe#66]
To to be stubbed out of their onCreate Methods (Refer to Moe's code in the references section of the wiki on how to do properly)

**Comment by raysarinas** [comment]
Just a note but it might be possible to have the onCreate methods and other button related things be stubbed out following a factory pattern

**Comment by TheBroMoe** [comment]
This issue is being closed because we have decided to keep button click method functionality within respective click variables rather than separating them
