### ISSUE TITLE
Update Database Security

### ISSUE THREAD

**Issue by jacobwong98** [CMPUT301F19T02/Vybe#71]
Until #43 is in progress/done, anyone is allowed edit any document. 

Need to update this security to be based on the request.auth.uid when this gets done.

https://firebase.google.com/docs/firestore/security/rules-conditions

**Comment by jacobwong98** [comment]
I have updated the security rules for Firestore. Please review if this rule is ok for now.
It can be seen under Database -> Rules

**Comment by raysarinas** [comment]
Aight sounds good
