### ISSUE TITLE
US 01.01.01 - Mood Event in Mood History

### ISSUE THREAD

**Issue by TheBroMoe** [CMPUT301F19T02/Vybe#8]
As a participant, I want to add a mood event to my mood history, each event with the current date and time, a required emotional state, optional reason, and optional social situation.

Story Points: 8

Dependencies: None

**Comment by raysarinas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Start Base Code](https://trello.com/c/nTl0Hwin/1-start-base-code)
